# Generated by Django 3.2.4 on 2021-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='user',
            field=models.CharField(default=None, max_length=225),
            preserve_default=False,
        ),
    ]
