# Generated by Django 3.2.4 on 2021-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_consumer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=225)),
                ('number_of_report', models.IntegerField(blank=True)),
            ],
        ),
    ]
